In [16]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

In [51]:
df1=pd.read_csv('/home/shivambhardwaj/Downloads/AB/barca.csv')
df2=pd.read_csv('/home/shivambhardwaj/Downloads/AB/barca_shuffle.csv')
df3=pd.read_csv('/home/shivambhardwaj/Downloads/AB/tomslee_airbnb_barcelona_1477_2017-07-23.csv')

In [21]:
df1.head()

,room_type,neighborhood,reviews,overall_satisfaction,accommodates,bedrooms,price,latitude,longitude
0,Shared room,Eixample,27,4.5,10,1.0,264.0,41.391617,2.162516
1,Shared room,Sants-Montjuïc,13,4.0,12,1.0,129.0,41.373268,2.170138
2,Shared room,Sants-Montjuïc,11,4.0,12,1.0,129.0,41.372360,2.169215
3,Shared room,Eixample,9,5.0,2,1.0,72.0,41.391836,2.154014
4,Shared room,Eixample,10,5.0,2,1.0,64.0,41.387623,2.148761

In [150]:
df2.head()

,0,room_type,neighborhood,overall_satisfaction,accommodates,bedrooms,price,latitude,longitude
0,poco visitado,Shared room,Eixample,4.5,10,1.0,264.0,41.391617,2.162516
1,poco visitado,Shared room,Sants-Montjuïc,4.0,12,1.0,129.0,41.373268,2.170138
2,poco visitado,Shared room,Sants-Montjuïc,4.0,12,1.0,129.0,41.372360,2.169215
3,poco visitado,Shared room,Eixample,5.0,2,1.0,72.0,41.391836,2.154014
4,poco visitado,Shared room,Eixample,5.0,2,1.0,64.0,41.387623,2.148761

In [52]:
df3

,room_id,survey_id,host_id,room_type,country,city,borough,neighborhood,reviews,overall_satisfaction,accommodates,bedrooms,bathrooms,price,minstay,name,last_modified,latitude,longitude,location
0,12331794,1477,41933599,Shared room,NaN,Barcelona,NaN,Eixample,0,0.0,5,1.0,NaN,211.0,NaN,5-bed mixed dorm at Sleep Green Y.H,2017-07-28 14:49:29.434152,41.387023,2.167047,0101000020E6100000C828CFBC1C56014060E63BF889B1...
1,12331935,1477,41933599,Shared room,NaN,Barcelona,NaN,Eixample,0,0.0,6,1.0,NaN,253.0,NaN,6-bed mixed dorm at Sleep Green Y.H,2017-07-28 14:49:29.431042,41.387658,2.167093,0101000020E6100000CD1FD3DA34560140320400C79EB1...
2,12332051,1477,41933599,Shared room,NaN,Barcelona,NaN,Eixample,0,0.0,8,1.0,NaN,289.0,NaN,8-bed mixed dorm at ACYHostel,2017-07-28 14:49:29.427665,41.387962,2.165981,0101000020E61000001B0FB6D8ED5301409E0B23BDA8B1...
3,4627938,1477,23968212,Shared room,NaN,Barcelona,NaN,Eixample,27,4.5,10,1.0,NaN,264.0,NaN,THE HIPSTEL hostel 1 BED IN DORM-10 Shared WC,2017-07-28 14:49:29.424265,41.391617,2.162516,0101000020E6100000289D4830D54C014060C77F8120B2...
4,12331497,1477,41933599,Shared room,NaN,Barcelona,NaN,Eixample,0,0.0,4,1.0,NaN,169.0,NaN,4-bed mixed dorm at Sleep Green Y.H,2017-07-28 14:49:25.542467,41.386288,2.165477,0101000020E6100000EAEBF99AE55201402B6B9BE271B1...
5,12018424,1477,64212374,Shared room,NaN,Barcelona,NaN,Sants-Montjuïc,13,4.0,12,1.0,NaN,129.0,NaN,12 Bed Mixed Dorm Ensuite,2017-07-28 14:49:23.585708,41.373268,2.170138,0101000020E61000006D74CE4F715C01405952EE3EC7AF...
6,12017913,1477,64212374,Shared room,NaN,Barcelona,NaN,Sants-Montjuïc,11,4.0,12,1.0,NaN,129.0,NaN,12 Bed Mixed Dorm Ensuite,2017-07-28 14:49:23.579837,41.372360,2.169215,0101000020E6100000EDF0D7648D5A0140562B137EA9AF...
7,11830051,1477,41807465,Shared room,NaN,Barcelona,NaN,Eixample,9,5.0,2,1.0,NaN,72.0,NaN,HEART OF BARCELONA : BED IN MIXED DORMITORY 2 ...,2017-07-28 14:49:17.169946,41.391836,2.154014,0101000020E6100000580229B16B3B01409EB29AAE27B2...
8,16552543,1477,46914366,Shared room,NaN,Barcelona,NaN,Sants-Montjuïc,0,0.0,9,1.0,NaN,73.0,NaN,Cama en dormitorio de 9 camas,2017-07-28 14:49:17.153288,41.373185,2.165882,0101000020E6100000E8F527F1B9530140CB2DAD86C4AF...
9,18212084,1477,76384135,Shared room,NaN,Barcelona,NaN,Eixample,10,5.0,2,1.0,NaN,64.0,NaN,DOUBLE SOFA-BED in sunny Barcelona,2017-07-28 14:49:17.147198,41.387623,2.148761,0101000020E6100000AF5C6F9BA9300140B51666A19DB1...
10,1823947,1477,9547606,Shared room,NaN,Barcelona,NaN,Sants-Montjuïc,67,4.0,16,1.0,NaN,45.0,NaN,Hostal esta 150 m del Camp Nou wifi,2017-07-28 14:49:12.852812,41.378011,2.129361,0101000020E6100000D905836BEE0801409E4319AA62B0...
11,17513179,1477,41092915,Shared room,NaN,Barcelona,NaN,Ciutat Vella,9,5.0,2,1.0,NaN,60.0,NaN,One bedroom flat by the sea,2017-07-28 14:49:12.837944,41.379429,2.190939,0101000020E6100000603FC4060B870140B613252191B0...
12,7965130,1477,41807465,Shared room,NaN,Barcelona,NaN,Eixample,6,4.5,8,1.0,NaN,289.0,NaN,PRIVATE ROOM FOR 8 PERSONS IN HEART OF BARCELO...,2017-07-28 14:49:08.666215,41.392055,2.154293,0101000020E61000008A03E8F7FD3B0140DC9DB5DB2EB2...
13,7965883,1477,41807465,Shared room,NaN,Barcelona,NaN,Eixample,4,4.0,6,1.0,NaN,193.0,NaN,ENTIRE ROOM IN HEART OF BARCELONA FOR 6 PERSONS !,2017-07-28 14:49:07.130490,41.392044,2.153721,0101000020E6100000D6AA5D13D23A0140E84B6F7F2EB2...
14,9111304,1477,2395550,Shared room,NaN,Barcelona,NaN,Sant Martí,5,4.5,2,1.0,NaN,133.0,NaN,Nice appartment for rent ;),2017-07-28 14:49:03.977842,41.407673,2.202132,0101000020E6100000F3CCCB61F79D01402A3BFDA02EB4...
15,7086254,1477,37143874,Shared room,NaN,Barcelona,NaN,Sants-Montjuïc,0,0.0,4,1.0,NaN,133.0,NaN,"alq.piso con terraza,acept mascotas",2017-07-28 14:49:03.974822,41.373105,2.163923,0101000020E6100000677FA0DCB64F0140AF7C96E7C1AF...
16,7968315,1477,41807465,Shared room,NaN,Barcelona,NaN,Eixample,20,4.0,4,1.0,NaN,144.0,NaN,NICE PRIVATE ROOM IN HEART OF BARCELONA FOR 4 ...,2017-07-28 14:49:03.971056,41.393532,2.152668,0101000020E6100000732A1900AA380140F9F6AE415FB2...
17,12033127,1477,64212374,Shared room,NaN,Barcelona,NaN,Sants-Montjuïc,8,4.0,4,1.0,NaN,114.0,NaN,4 Bed Mixed Dorm Ensuite,2017-07-28 14:49:01.879645,41.372717,2.169144,0101000020E61000005A84622B685A0140E5D4CE30B5AF...
18,12032919,1477,64212374,Shared room,NaN,Barcelona,NaN,Sants-Montjuïc,6,4.0,6,1.0,NaN,114.0,NaN,6 Bed Mixed Dorm Ensuite,2017-07-28 14:49:01.876339,41.372255,2.168686,0101000020E61000002E58AA0B78590140E162450DA6AF...
19,15748124,1477,101784868,Shared room,NaN,Barcelona,NaN,Ciutat Vella,0,0.0,1,1.0,NaN,111.0,NaN,habitacion en el born,2017-07-28 14:49:01.872776,41.387084,2.179327,0101000020E61000007E5182FE426F01400667F0F78BB1...
20,1211322,1477,6614322,Shared room,NaN,Barcelona,NaN,Sant Martí,0,0.0,14,1.0,NaN,121.0,NaN,Loft/Studio near Beach - Groups Offer,2017-07-28 14:49:01.869694,41.397277,2.190758,0101000020E61000005B9A5B21AC860140FC3905F9D9B2...
21,12018438,1477,64212374,Shared room,NaN,Barcelona,NaN,Sants-Montjuïc,9,4.0,6,1.0,NaN,114.0,NaN,6 Bed Mixed Dorm Ensuite,2017-07-28 14:49:01.865691,41.373335,2.170512,0101000020E6100000BB9A3C65355D0140E0B9F770C9AF...
22,7006472,1477,36213611,Shared room,NaN,Barcelona,NaN,Eixample,0,0.0,1,1.0,NaN,83.0,NaN,colchon en habitación compartida,2017-07-28 14:48:59.904058,41.396782,2.174835,0101000020E6100000BC9179E40F6601401CD2A8C0C9B2...
23,6624330,1477,8826561,Shared room,NaN,Barcelona,NaN,Eixample,28,4.0,4,1.0,NaN,84.0,NaN,Big shared room A/C with terrace 60,2017-07-28 14:48:59.901258,41.409357,2.176395,0101000020E6100000616C21C841690140C0B167CF65B4...
24,7659473,1477,40202792,Shared room,NaN,Barcelona,NaN,Sant Martí,0,0.0,2,1.0,NaN,84.0,NaN,Loft luminoso cerca del mar,2017-07-28 14:48:59.899104,41.395045,2.193919,0101000020E61000008E959867258D014063B9A5D590B2...
25,2806466,1477,14330519,Shared room,NaN,Barcelona,NaN,Gràcia,0,0.0,2,1.0,NaN,91.0,NaN,"Cozy flat in heart of Barcelona, Gracia",2017-07-28 14:48:59.896405,41.402218,2.153929,0101000020E6100000753FA7203F3B014067EE21E17BB3...
26,6638779,1477,34746872,Shared room,NaN,Barcelona,NaN,Eixample,0,0.0,2,1.0,NaN,91.0,NaN,HABITACION PARA GRUPO,2017-07-28 14:48:59.893138,41.380350,2.149504,0101000020E61000002FF834272F3201404D840D4FAFB0...
27,9994799,1477,8538802,Shared room,NaN,Barcelona,NaN,Eixample,0,0.0,3,1.0,NaN,102.0,NaN,Appartment in the city center,2017-07-28 14:48:59.888319,41.384249,2.158137,0101000020E6100000E84CDA54DD430140A6423C122FB1...
28,15401121,1477,41657332,Shared room,NaN,Barcelona,NaN,Eixample,4,5.0,1,1.0,NaN,100.0,NaN,Large studio 2 min walk from Pl. Catalunya.,2017-07-28 14:48:59.885607,41.387109,2.170089,0101000020E61000005646239F575C01405F7EA7C98CB1...
29,19723333,1477,139032216,Shared room,NaN,Barcelona,NaN,Ciutat Vella,0,0.0,2,1.0,NaN,97.0,NaN,Palau Calm,2017-07-28 14:48:59.883468,41.387041,2.175754,0101000020E6100000252191B6F1670140079B3A8F8AB1...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18808,6390297,1477,33314396,Private room,NaN,Barcelona,NaN,Gràcia,60,4.5,2,1.0,NaN,35.0,NaN,Charming magical double room,2017-07-23 13:07:00.137873,41.404517,2.160618,0101000020E610000001310917F248014088D68A36C7B3...
18809,12808754,1477,69818655,Private room,NaN,Barcelona,NaN,Sant Martí,86,4.5,2,1.0,NaN,29.0,NaN,"Habitación Calida, confortable y limpia",2017-07-23 13:07:00.135029,41.415847,2.196185,0101000020E6100000E0B9F770C9910140E29178793AB5...
18810,987773,1477,5420668,Private room,NaN,Barcelona,NaN,Gràcia,175,4.5,2,1.0,NaN,35.0,NaN,DOUBLE ROOM INDEPENDENT + BALCONY,2017-07-23 13:07:00.131889,41.411273,2.146525,0101000020E6100000075F984C152C0140295DFA97A4B4...
18811,19717341,1477,36320422,Private room,NaN,Barcelona,NaN,Nou Barris,2,0.0,1,1.0,NaN,30.0,NaN,Cozy single room close to the subway. Welcome!,2017-07-23 13:07:00.126094,41.427679,2.170364,0101000020E6100000725303CDE75C0140CE177B2FBEB6...
18812,10190539,1477,40802377,Private room,NaN,Barcelona,NaN,Gràcia,15,4.5,2,1.0,NaN,20.0,NaN,Cozy bedroom at sunny attic at Sagrada Familia,2017-07-23 13:07:00.111207,41.404972,2.169907,0101000020E61000004BE48233F85B0140DAE55B1FD6B3...
18813,19715049,1477,42688966,Private room,NaN,Barcelona,NaN,Sant Martí,1,0.0,1,1.0,NaN,22.0,NaN,Room in Guinardo,2017-07-23 13:07:00.103505,41.415076,2.179941,0101000020E610000021AD31E88470014060ADDA3521B5...
18814,13978164,1477,15920367,Private room,NaN,Barcelona,NaN,Eixample,38,4.5,2,1.0,NaN,18.0,NaN,HABITACIÓN DOBLE TIPO LOFT,2017-07-23 13:07:00.092939,41.382519,2.146106,0101000020E6100000B9FE5D9F392B0140A08CF161F6B0...
18815,18543180,1477,116645321,Private room,NaN,Barcelona,NaN,Sants-Montjuïc,8,5.0,1,1.0,NaN,30.0,NaN,habitación en alquiler en Barcelona,2017-07-23 13:07:00.085287,41.360286,2.137579,0101000020E61000005BEECC04C3190140749A05DA1DAE...
18816,3881519,1477,3242234,Private room,NaN,Barcelona,NaN,Sants-Montjuïc,144,4.5,1,1.0,NaN,23.0,NaN,Lovely Room near Plaza Espanya,2017-07-23 13:07:00.064436,41.376152,2.145993,0101000020E6100000368FC360FE2A01409929ADBF25B0...
18817,95560,1477,494228,Private room,NaN,Barcelona,NaN,Gràcia,345,4.5,2,1.0,NaN,24.0,NaN,"Nice privat room at ""Sagrada familia"": 4 streets",2017-07-23 13:07:00.054909,41.405847,2.168880,0101000020E61000007D96E7C1DD590140011764CBF2B3...
18818,5842289,1477,30333067,Private room,NaN,Barcelona,NaN,Ciutat Vella,130,4.5,1,1.0,NaN,22.0,NaN,Habitacion individual,2017-07-23 13:07:00.032187,41.383558,2.164810,0101000020E61000001A6EC0E787510140410FB56D18B1...
18819,14646319,1477,90932892,Private room,NaN,Barcelona,NaN,Horta-Guinardó,17,4.5,1,1.0,NaN,30.0,NaN,"Habitación acogedora, con patio interior.",2017-07-23 13:07:00.021724,41.412359,2.171575,0101000020E6100000567DAEB6625F01400B9B012EC8B4...
18820,19924067,1477,137608720,Private room,NaN,Barcelona,NaN,Sants-Montjuïc,0,0.0,2,1.0,NaN,30.0,NaN,HOLIDAY ROOM IN BARCELONA,2017-07-23 13:07:00.015579,41.374485,2.124191,0101000020E610000009A9DBD957FE0040D9EBDD1FEFAF...
18821,19916040,1477,43122645,Private room,NaN,Barcelona,NaN,Eixample,0,0.0,1,1.0,NaN,21.0,NaN,Simple single room,2017-07-23 13:06:58.883996,41.402674,2.181469,0101000020E610000010E7E104A6730140897956D28AB3...
18822,19924368,1477,123465110,Private room,NaN,Barcelona,NaN,Sant Andreu,2,0.0,2,1.0,NaN,30.0,NaN,Nice and comfortable room in Sant Andreu,2017-07-23 13:06:58.881882,41.439426,2.188036,0101000020E6100000E7C3B304198101408C81751C3FB8...
18823,19908443,1477,140988782,Private room,NaN,Barcelona,NaN,Sant Martí,0,0.0,2,1.0,NaN,30.0,NaN,Cómoda y acogedora habitación/Playa y Monumentos,2017-07-23 13:06:58.879896,41.396519,2.197509,0101000020E610000048533D997F9401400E9F7422C1B2...
18824,7103180,1477,37207299,Private room,NaN,Barcelona,NaN,Sants-Montjuïc,78,4.5,1,1.0,NaN,22.0,NaN,"Hab. Céntrica,cerca del Aeropuerto.",2017-07-23 13:06:58.877549,41.368139,2.134189,0101000020E610000012DDB3AED1120140EAB0C22D1FAF...
18825,19714952,1477,138937222,Private room,NaN,Barcelona,NaN,Gràcia,0,0.0,2,1.0,NaN,10.0,NaN,Cozy & Sunny Apartment in beautiful Gracia,2017-07-23 13:06:58.875410,41.405518,2.157742,0101000020E610000022A5D93C0E4301403CF88903E8B3...
18826,17951038,1477,123172101,Private room,NaN,Barcelona,NaN,Ciutat Vella,18,5.0,1,1.0,NaN,32.0,NaN,Cosy single room en el Raval,2017-07-23 13:06:58.872550,41.381539,2.166527,0101000020E61000003B35971B0C55014003931B45D6B0...
18827,9643682,1477,45495375,Private room,NaN,Barcelona,NaN,Eixample,80,4.5,2,1.0,NaN,32.0,NaN,Habitación en Sagrada Familia,2017-07-23 13:06:58.869735,41.398120,2.177551,0101000020E61000000DFAD2DB9F6B014017F19D98F5B2...
18828,19678251,1477,97874497,Private room,NaN,Barcelona,NaN,Sants-Montjuïc,6,4.5,2,1.0,NaN,30.0,NaN,Plaza españa,2017-07-23 13:06:58.867395,41.367651,2.142844,0101000020E6100000487023658B240140BDAB1E300FAF...
18829,18791554,1477,130792415,Private room,NaN,Barcelona,NaN,Gràcia,24,4.5,1,1.0,NaN,29.0,NaN,Habitación en el centro de Gracia,2017-07-23 13:06:58.864975,41.404222,2.161486,0101000020E61000004818062CB94A01406F29E78BBDB3...
18830,17991320,1477,13856967,Private room,NaN,Barcelona,NaN,Ciutat Vella,0,0.0,1,1.0,NaN,30.0,NaN,Great new flat in the center of Barcelona !!!!,2017-07-23 13:06:58.862651,41.379574,2.170590,0101000020E61000007632384A5E5D0140B9347EE195B0...
18831,19571589,1477,134563167,Private room,NaN,Barcelona,NaN,Sants-Montjuïc,2,0.0,1,1.0,NaN,18.0,NaN,Sunny single room at quiet and central area,2017-07-23 13:06:58.860324,41.376014,2.132733,0101000020E6100000BCCCB051D60F0140486B0C3A21B0...
18832,19828955,1477,140122861,Private room,NaN,Barcelona,NaN,Sants-Montjuïc,1,0.0,1,1.0,NaN,23.0,NaN,Habitación individual en loft compartido.,2017-07-23 13:06:58.858070,41.375908,2.145866,0101000020E610000064C91CCBBB2A01400327DBC01DB0...
18833,18928037,1477,50928708,Private room,NaN,Barcelona,NaN,Eixample,5,4.5,1,1.0,NaN,21.0,NaN,habitación con salida a balcón en Sagrada Familia,2017-07-23 13:06:58.853156,41.401955,2.179347,0101000020E6100000F015DD7A4D6F01405ABBED4273B3...
18834,16788998,1477,111522971,Private room,NaN,Barcelona,NaN,Gràcia,35,4.5,1,1.0,NaN,24.0,NaN,Single room in the heart of Gracia,2017-07-23 13:06:58.850042,41.406084,2.153433,0101000020E61000007104A9143B3A0140E5B67D8FFAB3...
18835,17535716,1477,35559163,Private room,NaN,Barcelona,NaN,Gràcia,9,4.5,1,1.0,NaN,24.0,NaN,Single room in the heart of Gracia,2017-07-23 13:06:58.847810,41.405000,2.159139,0101000020E6100000292504ABEA450140A4703D0AD7B3...
18836,18825927,1477,83810869,Private room,NaN,Barcelona,NaN,Eixample,4,5.0,2,1.0,NaN,34.0,NaN,WAKE UP BESIDE PASEO DE GRÁCIA,2017-07-23 13:06:58.845400,41.394932,2.154505,0101000020E61000003F8C101E6D3C01406A12BC218DB2...
18837,19529117,1477,134099717,Private room,NaN,Barcelona,NaN,Sants-Montjuïc,5,5.0,1,1.0,NaN,23.0,NaN,Habitación en Plaza España,2017-07-23 13:06:57.238229,41.368300,2.141541,0101000020E61000005858703FE0210140F38E537424AF...

In [53]:
df33=df3[['room_id','host_id','room_type','neighborhood','reviews','overall_satisfaction','accommodates','price','name']]

In [54]:
df33.head()

,room_id,host_id,room_type,neighborhood,reviews,overall_satisfaction,accommodates,price,name
0,12331794,41933599,Shared room,Eixample,0,0.0,5,211.0,5-bed mixed dorm at Sleep Green Y.H
1,12331935,41933599,Shared room,Eixample,0,0.0,6,253.0,6-bed mixed dorm at Sleep Green Y.H
2,12332051,41933599,Shared room,Eixample,0,0.0,8,289.0,8-bed mixed dorm at ACYHostel
3,4627938,23968212,Shared room,Eixample,27,4.5,10,264.0,THE HIPSTEL hostel 1 BED IN DORM-10 Shared WC
4,12331497,41933599,Shared room,Eixample,0,0.0,4,169.0,4-bed mixed dorm at Sleep Green Y.H

# Recommendation by top locations

In [81]:
grouped=df33.groupby('neighborhood')

In [82]:
df32=grouped.agg({'reviews':'mean','overall_satisfaction':'mean','accommodates':'sum'})

In [83]:
df32.sort_values(['reviews'],ascending=False)

                       reviews  overall_satisfaction  accommodates
neighborhood
Ciutat Vella         29.225650              3.151453         11477
Eixample             25.995885              3.107233         23562
Sants-Montjuïc       25.916103              3.084574          7185
Gràcia               24.235294              3.031909          5729
Sant Martí           20.573672              3.093995          7437
Horta-Guinardó       19.452713              2.921705          1786
Les Corts            18.887531              2.661369          1258
Sant Andreu          15.451220              2.824695           899
Sarrià-Sant Gervasi  15.273902              2.583979          2597
Nou Barris           14.872093              2.782946           575

In [108]:
def location_rec(location):
    Loc=grouped.get_group(location).sort_values(['reviews','overall_satisfaction'],ascending=False)
    return Loc[['name','price','overall_satisfaction']].head()

In [201]:
location_rec('Eixample').style.hide_index()

# Recommendation by top host

In [188]:
grouped1=df33.groupby('host_id')

In [189]:
df4=grouped1.agg({'reviews':'mean','overall_satisfaction':'mean','accommodates':'sum'})

In [195]:
df4.sort_values(['reviews'],ascending=False).head(10)

            reviews  overall_satisfaction  accommodates
host_id
494228   401.000000                   4.5             3
5223863  380.000000                   4.5             6
5428204  360.000000                   5.0             4
3424464  346.333333                   5.0             6
1541784  333.000000                   4.5             5
5756325  320.000000                   5.0             4
5472538  318.000000                   5.0             6
1414100  298.000000                   5.0             4
5157936  282.666667                   4.5             6
280070   280.000000                   4.5             6

In [191]:
def host_rec(host_id):
    Loc=grouped1.get_group(host_id).sort_values(['reviews','overall_satisfaction'],ascending=False)
    return Loc[['name','price','overall_satisfaction']].head()

In [193]:
host_rec(5223863).style.hide_index()

# Recommendation by room type

In [129]:
grouped2=df33.groupby('room_type')

In [130]:
df5=grouped2.agg({'reviews':'mean','overall_satisfaction':'mean','accommodates':'sum'})

In [131]:
df5.sort_values(['reviews'],ascending=False)

                   reviews  overall_satisfaction  accommodates
room_type
Entire home/apt  27.592317              3.064042         42731
Private room     22.244578              3.060177         19379
Shared room      15.235714              2.542857           395

In [132]:
def roomtype_rec(room_type):
    Loc=grouped2.get_group(room_type).sort_values(['reviews','overall_satisfaction'],ascending=False)
    return Loc[['name','price','overall_satisfaction']].head()

In [181]:
roomtype_rec('Entire home/apt').style.hide_index()

# Content based recommedation(by room name)

In [203]:
df35=df33.sample(frac=0.4, replace=False, random_state=1)

In [204]:
from sklearn.feature_extraction.text import CountVectorizer

count = CountVectorizer()
count_matrix = count.fit_transform(df35['neighborhood'])

In [205]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_sim2 = cosine_similarity(count_matrix, count_matrix)

In [156]:
df33 = df33.reset_index()
indices = pd.Series(df35.index, index=df33['name'])

In [206]:
def C_rec(name, cosine_sim=cosine_sim):
    idx = indices[name]
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:11]
    room_indices = [i[0] for i in sim_scores]
    return df35[['name','price','overall_satisfaction']].iloc[room_indices]

In [212]:
df_rec=C_rec('GORGEOUS EQUIPPED APTM WITH PARKING', cosine_sim2)

In [213]:
df_rec=pd.DataFrame(df_rec)

In [217]:
df_rec.where(df_rec['overall_satisfaction']>4).dropna().style.hide_index()